### ISSUE TITLE
Parse case name from OECI

### ISSUE THREAD

**Issue by KentShikama** [codeforpdx/recordexpungPDX#1240]
The format is always

```
State of Oregon vs [NAME]
```

We want to parse out the `NAME` part.

**Comment by victorjz** [comment]
This is the first issue I'm taking a deep look at. I'm not confident quite yet in assigning it to myself, so I'll start with offering my findings in case someone else thinks they can make quick work of it.

I'll offer that we're looking for the pattern `State of Oregon VS. [CASENAME]`
What's different than how it was presented in the previous comment
- casing of VS (though likely searching for the pattern with case insensitive, anyway)
- dot after VS
- just feel like calling it CASENAME to not mix it up with person names as seen elsewhere in the project

test data containing the pattern found in files in `src\backend\tests\fixtures\case_html\`
in particular, the test class, `case_details.py`, picks up `jd74.html` which contains the pattern 

it seems changes are necessary in 
- `case.py` will need the new property
- `record_parser.py` will need to parse for the pattern and store in the Case

I'm still making discoveries and I'll write again if I think I can assign this to myself. (I just used docker for the first time ever this week lol)

**Comment by victorjz** [comment]
I think I see what to do. But it seems I'm missing the option to assign this to myself.

- `case.py` add property in Case called case_name (because name seems to refer to the name of the defendant)
- `case_parser.py` add property in CaseParserData case_name
- `case_parser.py` add parsing statement in method feed for the case name and add to return statement
- `crawler.py` add statement in _read_case to replace case_name in case_summary
- ? add statements in test classes to check case_name

Giving it a shot...

**Comment by wittejm** [comment]
That all makes sense to me. I invited you to the codeforpdx org so now you can self-assign.

**Comment by KentShikama** [comment]
@victorjz I would call the field `defendant_name` instead of case_name.

**Comment by KentShikama** [comment]
Also you can assume that the HTML structure of OECI will never change (it is an old site that hasn't been updated in a while).

**Comment by victorjz** [comment]
I found in the test case_html files that the string may either have `vs` or `VS.` so I'll allow for both possibilities. Then I'll make it produce empty string if not found since I learned that soup can produce None and yield an exception if string operations are attempted on that.

The big hurdle now is one failed test: `test_crawler.py` failing `test_nonzero_balance_due_on_case` yielding a 0 balance instead of 1516.80
I welcome ANY thoughts on why adding a new member for case/CaseSummary causes this to fail.  I first thought having the new member at the end after balance caused problems, so the new member now comes first. That didn't fix it. And of course several other tests required consideration for the new member and those were adjusted to now pass.

I'll confess that I'm not using an IDE/debuggers kind of just out of exhaustion from learning docker and the project and trying to halt a rogue virtual machine chomping CPU (which is not rogue after all; containers are just persistent like that. oh...) :)

**Comment by wittejm** [comment]
I'm not able to take a close look at this right away, but you should file a draft PR with [WIP] in the name so we can see what you're doing. Kent may get to it before I do.

**Comment by victorjz** [comment]
I think I submitted the WIP pull request. Thanks!

**Comment by KentShikama** [comment]
Linking https://github.com/codeforpdx/recordexpungPDX/pull/1245
