### ISSUE TITLE
Add a manual section for "Paying Balances" instructions

### ISSUE THREAD

**Issue by wittejm** [codeforpdx/recordexpungPDX#1243]
The mockups in #1191 both have a link for more information on "Paying Balances". These need a destination.  

Tagging the leads @michellelsfong @michaelzhang43 for the in-progress manual redesign. 
 
Related to #1226 and #1227.

**Comment by michellelsfong** [comment]
Let's start with what that copy is. Would you mind drafting/finding it? @michaelzhang43

**Comment by michaelzhang43** [comment]
**Paying Balances** 
A client must pay or otherwise resolve any balance owed on a case before any charges on that case are eligible. This includes probation fees. It does not matter if a debt is "in collections." Court debt can be paid directly to the clerk's window in the Circuit Court in which the debt is owed. 

Additionally, as of June 15, 2020, it is the policy of the District Attorneys in **Multnomah** and **Douglas** Counties to object to expungement if a person owes ANY money to the State in ANY County. This includes debts on unrelated criminal cases, traffic tickets, and child support. This also includes any fines and fees owed to Municipal Courts (which do not show up in OECI or RecordSponge results).

**Comment by michellelsfong** [comment]
@michaelzhang43 what do you think of combining this & Assumption 1 #3?

![Screen Shot 2020-06-15 at 3 44 24 PM](https://user-images.githubusercontent.com/22565707/84713108-281c1f00-af1f-11ea-9def-86570e298789.png)

**Comment by michaelzhang43** [comment]
Hmm

Maybe we could cut the last paragraph (starting with 'additionally') and just link to that section of the Manual?

**Comment by michellelsfong** [comment]
Yup, sounds good!

@wittejm the change should just be copy. Let's add this to the end of point 3, assumption 1:

_A client must pay or otherwise resolve any balance owed on a case before any charges on that case are eligible. This includes probation fees. It does not matter if a debt is "in collections." Court debt can be paid directly to the clerk's window in the Circuit Court in which the debt is owed._ It does not matter if a debt is "in collections."

Court debt can be paid directly to the clerk's window in the Circuit Court in which the debt is owed.

Italics is what we currently have.

**Comment by wittejm** [comment]
Thanks! I'm updating the labels since it's an open issue now and the only remaining todo is edit the html.

**Comment by hmarcks** [comment]
Should we continue to update the [Google Doc](https://docs.google.com/document/d/1Su078uVl_tg0TuvyAUGr8n2IBQolhWl0H3rN1LUFRNI/edit?usp=sharing) or just treat this as the source of truth now? The main advantage I see of keeping the Google Doc up-to-date is that it has a nice interface to suggest and approve changes, but may not be worth the effort.

**Comment by wittejm** [comment]
Good question. I agree keeping them synced could be too much hassle. Can we only use github issues for this? It's a bit clunkier for documentation editing, but it's also nice to have all of our discussion in one place.

**Comment by hmarcks** [comment]
Sounds good to me

**Comment by swervinerv** [comment]
Picking up this ticket and just wanted to confirm what the copy changes were. Are the copy changes that @michellelsfong mentions [here](https://github.com/codeforpdx/recordexpungPDX/issues/1243#issuecomment-644874459) meant to be the first paragraph under bullet point 3 for Assumption 1 or are they meant to be appended on to what currently exists?

The way I read it the end result would look like the following screen shot
<img width="711" alt="Screen Shot 2020-06-26 at 6 45 52 PM" src="https://user-images.githubusercontent.com/6025685/85911927-621dd880-b7dd-11ea-9bd0-fa09ad6e110d.png">

**Comment by swervinerv** [comment]
Picking this up and wanted to check that I understood the copy changes correctly. Below is a screen shot of the changes made.

<img width="696" alt="Screen Shot 2020-06-26 at 6 49 32 PM" src="https://user-images.githubusercontent.com/6025685/85912001-df494d80-b7dd-11ea-8f6d-1b41c5271549.png">

**Comment by swervinerv** [comment]
@wittejm do we also want to add the link back to the manual from #1191 as part of this issue? If so should we display the link all of the time or only if the total balance due is more than $0?

**Comment by michellelsfong** [comment]
@swervinerv The copy should be this:

**3. The client does not owe money to the State, including probation fees, child support, traffic tickets.**
A client must pay or otherwise resolve any balance owed on a case before any charges on that case are eligible. This includes probation fees. It does not matter if a debt is "in collections." Court debt can be paid directly to the clerk's window in the Circuit Court in which the debt is owed. It does not matter if a debt is "in collections."

Court debt can be paid directly to the clerk's window in the Circuit Court in which the debt is owed.

**Comment by michellelsfong** [comment]
@swervinerv (Reposting because I noticed some errors!) The copy should be this:

**3. The client does not owe money to the State, including probation fees, child support, traffic tickets.**
A personal is not eligible for expungement if they owe money in the case they are trying to expunge. If a person owes money on any matter - including traffic violations, child support, and probation supervision - district attorneys will object in at least the following counties: Multnomah, Douglas. The Balance shows money the person owes to the Circuit courts, but does not show balances in Municipal courts, or for child support, or probation supervision fees. It does not matter if a debt is “in collections.”

Court debt can be paid directly to the clerk’s window in the Circuit Court in which the debt is owed.

**Comment by wittejm** [comment]
@swervinerv Yeah, we can include both links (from the summary panel, and from the in-case banner) in the PR. I'm inclined to say the link in the summary panel should always show even if the total is $0. My thinking is, a new user might see the $0 and still be curious to have the link for more information. Also, it might seem weird when a user does a few searches and the link is alternately visible or not. That said, I trust @hmarcks' intuition on the UI more than my own.

**Comment by hmarcks** [comment]
Agreed, and it simplifies things.

**Comment by wittejm** [comment]
completed with #1283
