### ISSUE TITLE
Update Manual with Add/Edit feature

### ISSUE THREAD

**Issue by hmarcks** [codeforpdx/recordexpungPDX#1308]
We want documentation for #1079

**Comment by wittejm** [comment]
Here's a rough draft on this section. These in-line images should be the html actual visuals. The charge-type select feature kind of requires the documentation page of #797 #1277 to be useful to a new user.

**Add & Edit Cases**

Sometimes the result of a Search doesn’t completely match a person’s true record. This can happen for a few reasons:

- The search returns the wrong person’s record: In the rare event that a different person’s Oregon reccord shares a birth date and name with the person of interest, these records may appear in the search result.
- One or more of a person’s cases cannot be found: If the record has a typo in the name or the incorrect birth date, it can be difficult to locate by searching OECI.
- A charge date or other piece of information for a particular case is missing or incorrect in OECI.
- The expungement analyzer could not classify the charge: Many of the records in OECI are older and have statutes that have been renumbered or repealed; or a charge has an irregular name not recognized by our analyzer.

If any of these issues appear in the record, they can be corrected with the Editing feature. You can also use the Editing feature to build a record from scratch and run an analysis without relying on OECI at all. 

Click the Enable Editing button after running a search:

![enable_editing_row](https://user-images.githubusercontent.com/2104990/87096469-c5edcb80-c1f7-11ea-8c11-5dbc7376d638.png)

You can now perform the following actions to change the contents of the record. These changes exist only temporarily in your session and will disappear if you run another search. The edits will persist if you navigate between Search and the Manual or other pages on recordsponge.com, but they will disappear if you leave the website.

Add Case: ![add_case_button](https://user-images.githubusercontent.com/2104990/87096362-7c04e580-c1f7-11ea-83ff-0f8097a7e5cc.png)

Create a new case from scratch that can be populated with new charges. You must provide the case Current Status, County, Balance, and Birth Year, all of which are used to provide complete analysis of the record.

Edit Case: 
You can edit any of these fields on an existing or newly created case by clicking the edit button ![img](https://user-images.githubusercontent.com/2104990/87096668-2c72e980-c1f8-11ea-8f10-64cc0510101f.png) in the case's header.  

Remove Case: 
Remove a case from the analysis by clicking the edit button and then Remove Case in the editing panel. With will display a [removed badge] badge on the case as well as all of the charges in the case. Any charges have have been removed will no longer affect the time eligibility of other charges.

Add Charge:
For a newly created case or an existing case on the record, you can add new charges. Creating a new charge requires that you provide the arrest date, disposition, and conviction date if the charge was convicted, and a charge type. Providng a charge name is optional and is a convenience to aid the readability of the Expungement results. 
The charge type is a concept specific to RecordSponge, and the types are defined based on a combination of the expungement rules and the information available in OECI including the charge level, charge name, and the applicable statute of the charge. You can click the [question-mark] button to visit the Expungement Rules page for our documentation on how charge types are defined and their eligibility rules. 

Edit Charge: 
For an existing charge you can edit any of this information

Remove Charge:
After clicking edit on a charge, you can remove it from the edit panel.
If some but not all of the charges on a case ought to appear in the result, you can remove only a subset of charges from the analysis instead of the entire case. The removed charges will no longer affect the eligibility of other charges.

**Comment by KentShikama** [comment]
Linking https://github.com/codeforpdx/recordexpungPDX/issues/1210

**Comment by wittejm** [comment]
completed with #1391
