### ISSUE TITLE
Create soft requirments for FillForms

### ISSUE THREAD

**Issue by monocle** [codeforpdx/recordexpungPDX#1644]
<img width="1135" alt="image" src="https://user-images.githubusercontent.com/120387970/212484710-44644d89-f4d1-472f-b181-1dbb0c71852c.png">

Per yesterday's conversation, all the fields should have a soft requirement, but there should be a way that the user can still bypass filling the forms in rare situations. 

@michaelzhang43 Should the heading "User Information" be "Client Information"? It seems like our primary "user" is the clinic staff that helps the client.

@KentShikama Thoughts on this https://github.com/monocle/recordexpungPDX/issues/14

**Comment by Matth5050** [comment]
Can someone let me know what a soft requirement is? Like making sure the user actually inputs something?

**Comment by Matth5050** [comment]
I have two proposed methods for this and I would appreciate anyone's input. 

1. The first is a checkbox that the user would have to check in order to download without filling in the forms. 
2. The second is a popup that alerts them that they haven't filled out the form but that they can continue to download if they want.

Let me know which you'd like or if we should go in another direction is better!

![Screenshot 2023-02-06 at 20 13 03](https://user-images.githubusercontent.com/95751146/217155861-4a805ffc-e0c9-4974-8d92-4e5328409eed.png)
![Screenshot 2023-02-06 at 21 15 39](https://user-images.githubusercontent.com/95751146/217155869-965e599f-f6b5-413f-9c1b-b863d0c00c10.png)

**Comment by michaelzhang43** [comment]
I like the second format better, but I think the first sentence should be phrased as "You are about to download an incomplete form." The forms even without the demographic info would still have the case and charge information, etc.

**Comment by monocle** [comment]
@Matth5050 I like the modal as well. Nice work with that!

**Comment by Matth5050** [comment]
@michaelzhang43 @monocle Thanks!
