### ISSUE TITLE
Connect /users/ endpoint to the database

### ISSUE THREAD

**Issue by erikjasso** [codeforpdx/recordexpungPDX#172]
Where we are using dummy data or stubbed calls replace w/data from the database reads and writes.

In `endpoints/user.py` do:

    from flask import g
    from expungeservice.database import user

The Flask `g` object will have a handle to the database stored on it in `g.database`. Use `user.create_user()` to create a user and `user.get_user_by_email()` to read a user, passing in `g.database` as the `database` parameter.

More details TBD.

**Comment by wittejm** [comment]
Starting to look at this I have a few questions / requests for opinions @NickSchimek @maxkwallace @erikjasso @a-ilango :
- Should a password length constraint be enforced here, e.g. 8 character minimum? Seems like yes to me. Options for status codes seem to be  `400 BAD REQUEST` or  `411 LENGTH REQUIREMENT`.
- What about allowed characters in the password? [This from Oracle](https://docs.oracle.com/cd/E11223_01/doc.910/e11197/app_special_char.htm#MCMAD416) resembles the convention I'm familiar with, and [this opinionated UX thread](https://ux.stackexchange.com/questions/72568/should-users-be-allowed-to-use-any-special-character-they-want-when-creating-a-p) makes a good case for not restricting any typable characters. I prefer the latter, but it could use a bit of testing to make sure that nonstandard characters don't break anything.
- User creation failure due to duplicate email currently returns a 202 status code but should be a 4xx, which one? `400 BAD REQUEST` ? [A reference for status codes](https://httpstatuses.com/)
- admin flag shouldn't be a field in the request and should just be set to False, since this endpoint is public-facing.
- hashing the password: the existing code hashes the password in the endpoint, whereas design.md says "hashed_password" is a field in the request. Hashing serverside makes sense because then the hash functionality is independent of the client, and the password is encrypted in transit by https -- (is that sufficient?). 

I expect to come up with a few more questions as I build this out :)

**Comment by wittejm** [comment]
(pinged specific folks but all opinions welcome)

**Comment by hmarcks** [comment]
I vote yes on character length, but no other requirements (unless ya'll think there should be some character restrictions).

**Comment by maxkwallace** [comment]
@wittejm re: user creation failure due to duplicate email, AFAIK the code should be a 422. See https://httpstatuses.com/422 , 400 would be used if e.g. the request itself was malformed.

Re: server-vs-client password hashing, see https://security.stackexchange.com/a/143857/38400 
I think we should hash on the server only (assuming the site will be deployed with SSL required). The small additional security from client-side hashing doesn't seem to be worth the extra complexity and implementation time.

If for some reason client-side hashing is really needed, it can be added later, using a boolean field on the users table that tracks whether the stored password was hashed on the client before being hashed on the server, or was only hashed on the server.

**Comment by NickSchimek** [comment]
>Should a password length constraint be enforced here, e.g. 8 character minimum? Seems like yes to me. Options for status codes seem to be 400 BAD REQUEST or 411 LENGTH REQUIREMENT

Sure, 8 char minimum... probably would also be good to enforce a number, and special char is used... However, I believe this validation should be done on the application side. Both on the frontend and backend.

>What about allowed characters in the password? This from Oracle resembles the convention I'm familiar with, and this opinionated UX thread makes a good case for not restricting any typable characters. I prefer the latter, but it could use a bit of testing to make sure that nonstandard characters don't break anything.

Agreed, latter sounds good.

>User creation failure due to duplicate email currently returns a 202 status code but should be a 4xx, which one? 400 BAD REQUEST 

See Max's comment ^^^

>admin flag shouldn't be a field in the request and should just be set to False, since this endpoint is public-facing.

Agreed.

>hashing the password: the existing code hashes the password in the endpoint, whereas design.md says "hashed_password" is a field in the request. Hashing serverside makes sense because then the hash functionality is independent of the client, and the password is encrypted in transit by https -- (is that sufficient?).

Agreed. Yes, hash on server side.

**Comment by NickSchimek** [comment]
>admin flag shouldn't be a field in the request and should just be set to False, since this endpoint is public-facing

Only the admin should have access to create a user. Correct? As the first phase of this app will not be publicly available.

**Comment by wittejm** [comment]
Great, thanks for the feedback everyone. Then:

- failure due to duplicate email will return a 422
- password minimum length of 8. I can add the check too for an alphabetic character, a numeric character, and a non-alphanumeric character. Should both the length and character failure conditions also return 422? 

> Only the admin should have access to create a user. Correct? As the first phase of this app will not be publicly available.

Ah, yea, looking again at the design doc I see that is the intention. Then the /users/ post method will require an auth token of the logged-in admin. This endpoint can check to see that the logged-in user is an admin before creating the new user. Looks like the failure status code for this would be `403 FORBIDDEN`

**Comment by maxkwallace** [comment]
> Should both the length and character failure conditions also return 422?

Yup, 422 ends up being a pretty common error code.

**Comment by NickSchimek** [comment]
Thanks for tackling this @wittejm Is this issue for creating the user endpoint? When I read your comment yesterday I thought it was for database constraints, but reviewing the issue now I see that it looks more like creating a user endpoint, which makes sense since the database wouldn't see the actual password...

I'd say regarding the password... check with Michael if we should enforce the user of certain characters as it's a balance between security and user experience. Although definitely enforce a minimum of length 8.

**Comment by wittejm** [comment]
@NickSchimek Yep, this issue is for implementing the complete /users/ endpoint, which naturally includes the database calls but (I discovered) requires more missing functionality that I hadn't realized was still todo.

And cool, I'll ask Michael for his opinion on the password character-types requirement.

**Comment by NickSchimek** [comment]
Ah now I see why this is called connect users endpoint... issue #47 should be marked as done... right?

**Comment by wittejm** [comment]
#47 does seem redundant with this issue, so it does make sense to close it.

**Comment by wittejm** [comment]
A new question: This endpoint needs to check that the logged-in user is an admin before the new account can be created. The logged-in user's email address is stored in the authorization header, and this information is decoded and checked at [auth.py](https://github.com/codeforpdx/recordexpungPDX/blob/583b1689a9f141377932d4851b9c24d5d52ba7ac/src/backend/expungeservice/endpoints/auth.py#L30-L43). 

But that only is in the function wrapper auth_required. To read the jwt payload in the users endpoint code, as far as I can tell there are two general options:
 - share the payload object to the rest of the app when it gets decoded in the auth_required wrapper. E.g., attach the object to the Flask's g (global) object, so that it can be read elsewhere while the request is being handled.
 - decode the auth header again in the users endpoint. That should mean abstracting the used in auth into its own function, such as using
` payload = decode_auth() ` 

I like the first approach, but I don't know if that's starting to abuse the global namespace or something. Is this fine or is there another solution I'm not thinking of?

**Comment by erikjasso** [comment]
> I like the first approach, but I don't know if that's starting to abuse the global namespace or something. Is this fine or is there another solution I'm not thinking of?

A pattern I've used is to store user attributes needed in SQL queries on `Flask.g` (`user_id`, permissions, etc.). I don't think that's an abusive use of `g`.
