### ISSUE TITLE
Export Record data as json for /search/ endpoint.

### ISSUE THREAD

**Issue by wittejm** [codeforpdx/recordexpungPDX#229]
The Record object and its members, including its Charge, Case, ExpungementResult, and Disposition objects, need to be converted to json data to return in a user search result. 

I see two general ways to do this: one is a programmatic approach that scoops up all of the public variables and properties on each of these objects. This could be done with a subclass of [JSONEncoder](https://docs.python.org/3/library/json.html ) recursively doing something like this:  

    import inspect
    result_data = {key: value for (key,value) in inspect.getmembers(record_obj) if key[0] != '_']

If the data objects are refactored so that everything that isn't a public field or a property (including getter/setter functions, etc.) has a leading '_' then this can return the exact data object we need. With @NickSchimek 's new PR #224 then the new Charge factory pattern could produce objects that look like this.

The other approach is manually exporting the list of relevant fields on each object, to construct a json object with only the explicitly named set of fields, evaluated (in the case of dynamically computed fields) at export time. I think the former programmatic approach would be cleaner and more maintainable. 

Is part of issue #48 

Includes @NickSchimek 's suggestion of refactoring data objects to use the property pattern.

### This task is done when:
 - Record, Charge, Case, ExpungeResult, and Disposition object data can be exported to JSON with exactly the fields required by frontend. 
 - design.md updated to reflect the format of the returned json data.

**Comment by wittejm** [comment]
Related question: the Charge object includes secondary dynamically computed properties like acquitted(), recent_conviction() and others. Should any/all of those be included in the returned json? In this case the members of the returned data should all be listed in the design.md Data Model section. 

Pinging @NickSchimek and frontend folks @maxkwallace @hmarcks @cjbreaux  but all opinions welcome.

**Comment by maxkwallace** [comment]
@wittejm I have a few opinions here. If I understood correctly (correct me if wrong), we're asking the general question: how do we serialize server-side objects into JSON for the client? (Sidenote: almost every webapp has to solve this problem, so there are many existing solutions.) The two general proposed solutions are:

A: By default, serialize all public fields and properties on objects of the relevant types. 

B: For each property/field on an object of a relevant type, opt-in to having it serialized.

With (A) we run the risk of accidentally leaking data if someone adds a property to one of those objects without intending for it to be serialized. With (B) we run the risk of not having fields serialized because someone forgot to add them to the list. There is a convention you have to remember in both cases. I don't think there's a big difference in the code. I think the difference is just: in (A) you iterate over all the properties/fields, and in (B) you only iterate over the properties/fields included in the opt-in list.

A is more convenient (less typing) and comes with a (not sure how big) security risk. In the abstract I'm fine with both options, it depends on how it's coded. I think the important thing is that the relevant convention in each case is well-documented in the code to make sure people don't forget how the serialization functionality works and that they use it correctly.

---

Separate question: should computed properties be included in JSON?

My $0.02: It depends, but generally no. I've done both. Some things are simply unfeasible to compute client-side in which case you must include the computed data. It also depends on whether the underlying data is mutable.

In general, as long as the logic is simple, what's worked best for the teams I've been on is to duplicate the computation method logic on the client and the server and have a very visible block comment on both methods stating that the logic is duplicated and you must change it in both places (if it needs to be changed).

But this app doesn't seem to be doing much on the frontend so I'd actually lean more towards duplicating the data. Especially if it's immutable and we'll never need to recompute that data on the client.

The important thing is having clear comments and documentation stating what approach you are using so no one gets confused about which attributes of an Object or JSON object are the "source of truth".

One thing you could try is putting computed data in a sub-object, something like this:

```
{
  a: 1,
  b: 1,
  computed: {
    a_plus_b: 2
  }
}
```

**Comment by NickSchimek** [comment]
Thank you @maxkwallace for the detailed explanation and pros/cons of both approaches.
To answer @wittejm questions about the public methods such as `acquitted(), recent_conviction()` - These should not be included in the JSON (there's also another refactoring coming that is going to remove some of those methods). The only values that should should be in the JSON are all attributes of the case, charge, expungment results, and disposition objects. Currently there is no issue with all the attributes being added (public and private), and was just planning to just serialize all the fields as shown in option A above. I don't see the Record data objects being changed in the future to add new attributes, and even if they do the likelihood of them being OK to convert to JSON is high. 

As max said, there are a lot of solutions out there for this. I have this code snippet that I've used earlier for this project to serialize and print json.
```
import json
print(json.dumps(crawler.result.cases, indent=4, default=convert_to_dict))
```

It prints out all the attributes in all 4 data objects that we need. We could update and add a `to_json` instance method to the Record class:
```
import json

    def to_json(self):
        return json.dumps(self.cases, default=convert_to_dict)
```
The default convert_to_dict is necessary for the date fields since they're a date object
And then the controller can call it
```
record.to_json
```

If we put this under a system test then if any fields are updated in the future we can ensure the test fails, safe guarding against any fields being added that we may not want in there, and as max said we should document it too. 

Currently, I think  the only problem is the `total balance in cents` field with the above method I believe  a getter method using the @property tag should fix this so that it returns total balance with a precision of two.

**Comment by NickSchimek** [comment]
I'm open to other solutions, but I usually like to go the simplest route first, and update later if necessary.

**Comment by NickSchimek** [comment]
sorry if something above doesn't make sense. I need sleep. goodnight

**Comment by NickSchimek** [comment]
oh yeah, here is the obj to dic method
```
    def convert_to_dict(obj):
        if obj.__class__.__name__ == 'date':
            return obj.strftime('%m/%d/%Y')
```

**Comment by wittejm** [comment]
Thanks for the rundown @maxkwallace . At first guess I think that any potentially sensitive information can just be formatted as private-named fields/functions so we can have a programmatic serialization approach that  won’t capture any of that. The tradeoffs of those two general approaches are definitely good to keep in mind. 

@NickSchimek  As far as I can tell the built-in or standard functions for converting an object directly to json or a dictionary like __dict__ and others don’t evaluate functions or capture properties, and using the property pattern does seem like the best way to handle balance_due, for example (and others). This all definitely depends on how the objects look in the completed version of the expunger code, and this conversation might be more useful after your refactoring is completed / merged. 

It’s looking like most of the pieces are in place to implement the /search/ endpoint and I’m excited to make that available for integration in the frontend, so I may be looking ahead a little bit here.

**Comment by NickSchimek** [comment]
I think you might be right, but that doesn't mean we can't still use it. There are so many ways to solve this.
The frontend doesn't need this to implement their search feature. They just need to know the JSON format we will return, which I should probably get documented as I think it gets lost in slack

**Comment by NickSchimek** [comment]
@wittejm Have you seen this? https://kite.com/python/docs/flask.jsonify 
it might be worth looking into.

**Comment by wittejm** [comment]
This was completed with #434
