### ISSUE TITLE
Exclude juvenile charges from the expungement analysis

### ISSUE THREAD

**Issue by NickSchimek** [codeforpdx/recordexpungPDX#236]
## Description
Blocked by Issue #202 and #235

### This task is done when:
 - Juvenile cases are excluded from the expungement analysis
 -

**Comment by KentShikama** [comment]
Currently juvenile charges run through the expunger as a "normal" charge that does not block. Somewhere along the way an assumption was made that specifying that the charge does not block was sufficient, but that doesn't seem to be the case. Notably, one criteria is that "[a]t least five years have elapsed since the date of the person’s most recent termination". @wittejm We should probably look into this further eventually.
