### ISSUE TITLE
Record Object Testing Improvement

### ISSUE THREAD

**Issue by gingerben93** [codeforpdx/recordexpungPDX#253]
### Description
The Record Object exists with minimal desired functionality. The way it is tested should be more clear. Adding a factory model to how it is tested would make it more clear and follow the standard of the project. Changes to the other factories or models may be required to complete this task and is OK.

### This task is done when:

- [x] Factory model is created for Record Object
- [x] Factory model is used to test the Record Object

**Comment by gingerben93** [comment]
I also made some other changes you referenced earlier.
`def total_balance_due(self):
        total = 0`
Now returns int
` def total_balance_due(self):
        total = 0

        for case in self.cases:
            total += case.balance_due_in_cents

        #for two decimal places
        return round(total/100.0,2)`
now rounds to two decimal places

**Comment by gingerben93** [comment]
I finished the goals. The record_factory is very bare bones, but I think more test will be added.
The testing is cleaned up and looks a lot nicer.

I'm struggling with finding a nice way to test the record object charges for correctness because of the objects are nested and I can't think of a clean looking way to do it.

**Comment by NickSchimek** [comment]
Very nice! Thank you! I checked out your branch and everything looks great. It is OK the RecordFactory is a bit barebones. We can implement a few more options on an as needed basis. 
I see what you mean by finding a way to check the charges method. 
This is probably a bit overkill, but I would implement these three tests.
Test empty case list
FYI: Since the `@property` tag is used on the charges method there is no need to put the `()`
```
record = RecordFactory.create([])
assert record.charges == []
```
Test one case one charge
```
# setup
case = CaseFactory.create()
charge = ChargeFactory.create(case=case)
case.charges = [charge]

#test
record = RecordFactory.create([case])

assert len(record.charges) == 1
assert record.charges[0] == charge
```
it would be nice to not have to do this
```
case = CaseFactory.create()
charge = ChargeFactory.create(case=case)
case.charges = [charge]
```
Unfortunately the CaseFactory is a bit bare bones too, and I didn't have much experience when I first created this, but now I know how I would do it differently. It is something that all the test factories could improve upon. Perhaps to get it out of the way you can put it up in a setUp() method.

OK. for the third test. test two cases with multiple charges
```
#setup
case_zero = CaseFactory.create()
charge_zero = ChargeFactory.create(case=case_zero)
case_zero.charges = [charge_zero]

case_one = CaseFactory.create()
charge_one = ChargeFactory.create(case=case_one)
charge_two = ChargeFactory.create(case=case_one)
case_one.charges = [charge_one, charge_two]

#test
record = RecordFactory.create([case_zero, case_one])

assert len(record.charges) == 3

assert record.charges[0] == charge_zero
assert record.charges[1] == charge_one
assert record.charges[2] == charge_two
```
There may be some syntax and semantic errors in the above code, but it should give you one idea of how to test it. Let me know what you think. 

I've been kind of bad in my tests and have been putting multiple assertions under one test method, however.. Ideally you should have one assertion per test method.

**Comment by gingerben93** [comment]
@NickSchimek Thanks for the quick feed back! Your suggestion for testing the charges method looks pretty clean and I might try something along those line. 

I do understand your concern that a standard unit test shouldn't have multiple asserts because it should fail for only one reason. This case might be OK because you're testing the index of an array so it would be failing for the same reason ever time. Does that make since? Another quick example I can think of would be checking for value in a range:
`assert some_value <= 100
asset some_value >=0`
This seems in the spirit of a unit test even though it has multiple asserts. Thoughts about that?

After I clean it up one more time I'll probably submit a pull request. I want to try simulating an agile work environment by finishing something about once every two weeks (incremental improvement!). I'll submit another ticket about this If I feel there is something else that needs to be done and assign it to myself or pick something else.

Cheers!

**Comment by NickSchimek** [comment]
Awesome! 
Yes, I have thoughts about that :)
The main issue with having multiple asserts is that it can be difficult to tell by the description of the method what is failing. Each method should have a single responsibility, but if our test method is testing multiple things it is kind of hard to name it, and that named method comes up as failing.
For example this test could be generically named as:
```
def test_charge_method(self):
  #setup
  case_zero = CaseFactory.create()
  charge_zero = ChargeFactory.create(case=case_zero)
  case_zero.charges = [charge_zero]

  case_one = CaseFactory.create()
  charge_one = ChargeFactory.create(case=case_one)
  charge_two = ChargeFactory.create(case=case_one)
  case_one.charges = [charge_one, charge_two]

  #test
  record = RecordFactory.create([case_zero, case_one])

  assert len(record.charges) == 3

  assert record.charges[0] == charge_zero
  assert record.charges[1] == charge_one
  assert record.charges[2] == charge_two
```

And then if any of those assertions fail then the assertions after the failed assertion are not ran, hence you immediately do not get the full scope of the issue causing the failure, and it can make it a bit harder to figure out what is going on. 
Plus the failure will say something like:
```
failed: test_charge_method:
expected: 4 got 3
some stack trace...
```
With this test three of the assertions are not ran, because the first assertion failed. If those last three assertions ran you can immediately tell if the charge method is totally bombing or partially correct.

You can have multiple test classes in one test file so we can do something like this:
```
class TestSomethingHere(unittest.TestCase):
    def setUp(self):
         some setup stuff

    some method tests here

class AnotherClassHere(unittest.TestCase):
    def setUp(self):
         some setup stuff

    some method tests here

class TestChargeMethod(unittest.TestCase):
   
    def setUp(self):
        self.case_zero = CaseFactory.create()
        self.charge_zero = ChargeFactory.create(case=case_zero)
        self.case_zero.charges = [charge_zero]

        self.case_one = CaseFactory.create()
        self.charge_one = ChargeFactory.create(case=case_one)
        self.charge_two = ChargeFactory.create(case=case_one)
        self.case_one.charges = [charge_one, charge_two]

    def test_num_cases(self):
      record = RecordFactory.create([self.case_zero, self.case_one])

      assert len(record.charges) == 3

    def test_zero_index_returns_correct_object(self):
      record = RecordFactory.create([self.case_zero, self.case_one])

      assert record.charges[0] == self.charge_zero

    def test_first_index_returns_correct_object(self):
      record = RecordFactory.create([self.case_zero, self.case_one])

      assert record.charges[1] == self.charge_one

    def test_second_index_returns_correct_object(self):
      record = RecordFactory.create([self.case_zero, self.case_one])

      assert record.charges[2] == self.charge_two
```

As I've said I've been lazy and I haven't done this in my tests, but I've then had situations where all the assertions are not ran, because of a failure, and I have to take extra time to understand the full scope of the issue.
