### ISSUE TITLE
Containerize Flask app

### ISSUE THREAD

**Issue by erikjasso** [codeforpdx/recordexpungPDX#44]
Build a Docker container for our Flask application. This container will run the Python/Flask code.

This involves:
- adding a Docker file to `src/backend/expungeservice`
- adding a stanza to `docker-compose.yml`
- adding targets to `Makefile` for building the image, starting and stopping the container (see how the database container is done)
- flesh out `src/backend/expungeservice/wsgi.py`
- pick a base image, such as [library/ubuntu](https://hub.docker.com/_/ubuntu/) to reference in `src/backend/expungeservice/Dockerfile`

**Comment by erikjasso** [comment]
Working on this

**Comment by erikjasso** [comment]
Opened pull request. https://github.com/CodeForPortland/recordexpungPDX/pull/81

**Comment by wittejm** [comment]
@erikjasso  I think the recent update from psycopg version 2.7 to 2.8 by dependabot broke this image build. 

According to the doc: http://initd.org/psycopg/docs/faq.html#problems-compiling-and-installing-psycopg2

Version 2.7 included automatic install of a postgres dependency but 2.8 takes that out and the dependency needs to be installed manually to build the package from source. 

Alternatively the pre-compiled package  psycopg2-binary can be used instead (according to the install doc), but is not recommended. 

Adding the prerequisite libpq-dev to the Dockerfile fixes the issue. Is that the best solution?

Tagging @a-ilango too because we were talking about this bug earlier.

**Comment by NickSchimek** [comment]
>Adding the prerequisite libpq-dev to the Dockerfile fixes the issue. Is that the best solution?

Yes, I would say that it is the best solution

**Comment by erikjasso** [comment]
Thanks for digging into this, Jordan. Sounds like you hit on the correct solution.

**Comment by erikjasso** [comment]
@wittejm Is this ready to be closed?

**Comment by wittejm** [comment]
@erikjasso It sure is!  Thanks for spotting it, will close now
