### ISSUE TITLE
Endpoint: /api/search

### ISSUE THREAD

**Issue by erikjasso** [codeforpdx/recordexpungPDX#48]
Endpoint for searching the remote site. The web app will `POST` to this endpoint with search params in the body, and the endpoint will make a request of the remote site.

Data format TBD.

**Comment by erikjasso** [comment]
See `src/backend/expungeservice/endpoints/hello.py` for an example of a Flask endpoint

**Comment by maxkwallace** [comment]
@ash-tamraz noticed this was assigned to you so I assume you're working on it. Moved it to "In Progress", feel free to move it back to "Backlog" and let me know if you think that's more appropriate.

**Comment by wittejm** [comment]
Current design based on #361 and subsequent discussion:

**GET** /api/search
- Checks request for a cookie containing the encrypted user credentials for the OECI site
- Search query params: first name, last name, middle name, birthday.
- Decrypts the cookie, logs into the OECI site, and performs a record search.
- Runs the expunger on the search() result.
- Returns the analyzed record in this data format: https://github.com/codeforpdx/recordexpungPDX/blob/master/doc/results_format.json
- Logs the username and date (or the approximate date?) that the search was performed
- Logs some summarizing stats about the expungement result. See issues: #49 , #119 .

@maxkwallace you suggested this should be a GET method because it only saves logging data, but I still hesitate on that because the data we're recording is a processed result from the remote search results, e.g. number of eligible/ineligible records, or other non-trivial data collection. Feel a lot more like a POST.
