### ISSUE TITLE
Handle case in which person has a record with an open case

### ISSUE THREAD

**Issue by KentShikama** [codeforpdx/recordexpungPDX#586]
Currently the frontend search result of a person with an open case would be to have all charges that are type eligible shown as "Unknown type or time eligibility" as reported on https://github.com/codeforpdx/recordexpungPDX/issues/584. 

Perhaps we should instead just have a the search result return a giant "there is an open case" banner at the top and show all time analyzer result areas as "Not analyzed".

**Comment by hmarcks** [comment]
@KentShikama the original plan was to show the disposition and time eligibility as open, similar to this mockup. I like the idea of a banner as well to make it more clear:

![open-charge](https://user-images.githubusercontent.com/6887982/69600655-13a22480-0fd7-11ea-9cda-effe6b79e45a.png)

cc @NickSchimek

**Comment by NickSchimek** [comment]
It would probably be good to have a link on the banner to run the same request that will tell the backend to ignore the open cases. This would be good for those edge cases where the user knows there are no open cases, but our app is reporting that there is. They would still be able to get their analysis that way.

**Comment by hmarcks** [comment]
Ohh I like it, here's what that could look like:
![open-charge-v2](https://user-images.githubusercontent.com/6887982/69664444-03795c00-104e-11ea-8899-2e3fba35fcd1.png)

**Comment by hmarcks** [comment]
I wonder if a better approach is to give the option to mark any open charges as either convicted or dismissed, and possibly add a date to give an estimate with the open case considered. I think just ignoring the charge gives an accurate picture of what could be expungeable because the case will eventually have to be considered. It's obviously more involved but thought I'd throw it out for consideration.

**Comment by wittejm** [comment]
@hmarcks I think that (also applied to #652) would be an awesome feature. 

Showing a warning and skipping the open cases or missing disposition errors in the analysis seems like an ok (not great) stopgap for the issue. And in fact the expunger can always do the time analysis, and the frontend can just check whether there are errors attached to the record. If there are errors, it can show the informative warning message for the error, with the button to ignore and show analysis. That way the expunger doesn't have to run twice to get the same data, to do something a user will probably want to do anyway.

Thinking through your suggestion a little, I think the backend would need an additional endpoint that accepts the record data object back from the frontend, including the "fixed" charge dispositions, so that the crawler doesn't need to trying merging a fetched OECI record with the edited data from the user. 

I tried thinking through another idea of a stopgap solution for if these errors are present, to assign a default disposition, lets say `convicted`  for any of these errored charges. It would need to still be disclaimed as an unreliable result, and since the user would need to verify the time analysis anyway it probably wouldn't really add value to the result. 

But I think the idea of "mark and rerun" should def go on the list of future enhancements.

**Comment by hmarcks** [comment]
I like the stopgap idea of a default disposition of *convicted* for unknowns (as long as it's clearly disclaimed like you mention). I think it's better than ignoring because that will never be a real scenario. Although wouldn't we need a convicted date to get an accurate time eligibility result?

Here's what it could look like if we added the ability to override disposition which includes a date if convicted:

![override-disposition](https://user-images.githubusercontent.com/6887982/71335097-ba121480-2506-11ea-8a73-94f3e604d53d.png)

**Comment by wittejm** [comment]
This issue is half-completed (showing an error banner for an open case) and the other half is covered by the issue #687
