### ISSUE TITLE
Consolidate documentation across the project

### ISSUE THREAD

**Issue by KentShikama** [codeforpdx/recordexpungPDX#638]
Currently, we have 3 different locations that seem to give various details about the project:

- https://codeforpdx.github.io/recordexpungPDX/
- https://github.com/codeforpdx/recordexpungPDX/wiki
- https://github.com/codeforpdx/recordexpungPDX/tree/master/doc

We should stick to one location or else it becomes confusing: I've been on the project for 2 months now but I only discovered last week about the expungement flow chart https://www.draw.io/#G1aLwddaCPTUMazWIat-U6nMyWf0Qdgvfe from @wittejm . I would suggest https://github.com/codeforpdx/recordexpungPDX/tree/master/doc but I have no strong preferences.

**Comment by hmarcks** [comment]
Agreed. I vote for the wiki but am fine with any.

**Comment by wittejm** [comment]
I think the `readme.md` and `doc/` is the place to keep everything that's important to for getting started as a contributor. 

Since there's unavoidably "useful" documentation that isn't essential reading for devs we should still have the wiki IMO. A sentence in the readme encouraging people to see the wiki for the useful-but-less-organized documentation is worthwhile.  

Deleting the io page sounds great.

**Comment by wittejm** [comment]
I deleted the io page, so I'm closing this issue.
