### ISSUE TITLE
Integrate user / account functionality

### ISSUE THREAD

**Issue by hmarcks** [codeforpdx/recordexpungPDX#731]
![69019529-a78c4480-0976-11ea-853d-4c69937e0deb](https://user-images.githubusercontent.com/6887982/72584874-584c8c80-38b1-11ea-81a7-c0097f73f862.png)

Accessible validation technique: https://www.w3.org/WAI/WCAG21/Techniques/aria/ARIA19

### This task is done when:
 - Add users / accounts if you're an Admin
- Edit other account if you're an Admin
- View a list of all users if you're an Admin
- Edit your account

_We may want to split this up_

**Comment by ForrestLonganecker** [comment]
@KentShikama @wittejm Looking into how we are able to get user information about the currently logged in user for their account page, so they can then edit their information. 

- How will we be able to do a `get_from_user_id` without returned `user_id` to begin with?

Would we have a separate endpoint called `account` that would return the user information that matches the decoded cookie that comes through with the request?

![image](https://user-images.githubusercontent.com/42503418/72672804-fa38ba00-3a14-11ea-8737-f3106226431b.png)



---

Slightly related to this, we will also need to provide information upon `login` to the front end that will let us conditionally render the navbar depending on the current user being `admin` or `non-admin`. I can see two ways of handling this right off the bat.

- option 1:
Create an endpoint along the lines of `/is_admin` that sends back success or fail based on the the value of the cookie that comes along with the request. We can make this check in the `componendDidMount`/`componentDidUpdate` and render the `Admin` link based on the response.

- option 2:
Return some information from initial login that will tell us if the user is `admin` or `non-admin`, flip an `isAdmin` state variable in redux depending on the value and render conditionally based on that. 

The drawback here being that someone who knows what they are doing can use react-dev-tools to manually change this and look at the `Admin` page anyways. 

We can still protect sensitive information in this approach by doing something similar to what has already been done in the `UserList` component with all components that need to be hidden from `non-admins` and can take it a step further by triggering a redirect in addition to rendering the `You are not authorized to see this information` error. After redirecting we can switch the redux variable back to `isAdmin = false` and hide the `Admin` link again.

---

I am open to suggestions and input here, please let me know what you think the best approach for the time being would be!

**Comment by wittejm** [comment]
The new approach for a user to get their own data is is that there's now a `/user` endpoint for the frontend to say "get my own user info" without providing a `user_id`, whereas the admin-protect  `/users` endpoint does provide `user_id`s can and use them to `get` or  `put` any user's data with /users/[user_id]`. The design doc is out of date for these endpoints, which we need to address separately. 

For rendering the admin button in the nav bar, I like option 2 because it avoids making an extra request to the backend, and the possible user hack is purely cosmetic if the endpoints providing data are still auth-protected. 

@KentShikama since you refactored the login flow for the api, what do you think of providing the admin login flag  in the login endpoint response, which is currently empty?

**Comment by KentShikama** [comment]
Yeah providing an isAdmin flag on a successful endpoint response sounds good.
