### ISSUE TITLE
Main login integration

### ISSUE THREAD

**Issue by hmarcks** [codeforpdx/recordexpungPDX#75]
Integrate the UI to log in to the app, reset password, and set password.

User flow: 
![login flow](https://user-images.githubusercontent.com/6887982/54334025-e137cf00-45e1-11e9-9121-5aaa8fabc2a2.png)

Template w/ error messages: http://dev.huntermarcks.net/log-in
Design system: http://dev.huntermarcks.net/design-system

**Comment by htharker42** [comment]
Thanks Hunter!

**Comment by maxkwallace** [comment]
This issue is mostly done as of https://github.com/codeforpdx/recordexpungPDX/pull/285
Thanks @cjbreaux !

Here's what I think is left:
- Loading state for the 'send password reset email' button
- Change routes to the login page after resetting password
- Loading state for the login buttons

There will probably be at least a few other small issues we find since the complete feature is far from done. I recommend keeping this issue open for now. The loading states and validation/error message won't be able to be fully tested to final requirements (full "integration testing" for the feature) until we can link this functionality up with the AJAX requests to the backend.

@cjbreaux going to unassign you for now, but definitely reassign yourself if you're still working on this!

**Comment by hmarcks** [comment]
Closing because the account feature has been removed
