### ISSUE TITLE
Merge Contempt with CivilOffense, and documentation

### ISSUE THREAD

**Issue by michaelzhang43** [codeforpdx/recordexpungPDX#967]
This issue consolidates non-criminal offenses of certain categories into the Chargetype "CivilOffense"

1. Get rid of Chargetype Contempt of Court , and funnel those cases into CivilOffense
2. CivilOffense should still contain charge 01-99 and Extradition
3. Then add this to the Civil Chargetype documentation:

Expungement, generally speaking, only applies to criminal offenses. Civil offenses and administrative procedures – even those subject to punishments including jail time – are not eligible for expungement. The distinction between criminal and civil charges is far from clear. See, e.g. Brown v. Multnomah County Dist. Court, 570 P. 2d 52 - Or: Supreme Court 1977 ('There is no easy test for when the imposition of a sanction is a "criminal prosecution" within the meaning of the constitutional guarantees.') However, at least the following are not eligible under the expungement statute:
- Contempt of Court
- Extradition/Fugitive Complaint
- Parking tickets

### This task is done when:
 -
 -

**Comment by wittejm** [comment]
I'm pretty sure this isn't technically accurate because
- A violation conviction is eligible
- A violation is a type of civil charge
- So a violation dismissal is ineligible because it's not covered under "dismissed criminal charges".

Also Contempt of Court has been separated out as its own charge type as of 2 weeks ago, since it's identified by name instead of chapter number. So I think it's a potentially confusing example to use here.

**Comment by michaelzhang43** [comment]
Good point. The first pass at this Chargetype description I posted above uses a 'civil-criminal distinction' to justify Contempt of Court not being eligible.  This distinction is sometimes used to quickly distinguish between criminal matters and non-criminal matters, although the issue is more complicated. SKIPPABLE EXPLANATION IN BRACKETS
[
The full rationale of why Contempt of Court is not eligible is found in the case, State v. Coughlin, 311 P. 3d 988 - Or: Court of Appeals 2013, available at 
https://scholar.google.com/scholar_case?case=8724592606966552813&q=258+Or+App+882&hl=en&as_sdt=4,38
("A person who has been found in contempt has not been "convicted * * * of any offense" for purposes of ORS 137.225(6)(b). Such a contempt finding does not, therefore, render a person ineligible to have a criminal conviction set aside under ORS 137.225(1). ") (this case decides that a Contempt of Court does not block other convictions, but also functions as an explanation of why Contempt of Court is not eligible for expungement). 

Courts are motivated to find a clear distinction between criminal and non-criminal matters because the Oregon and US constitutions each provide for strong protections in criminal matters (but not non-criminal, i.e. civil, matters). But in fact, courts are pretty confused as to the distinction. See, e.g. Brown v. Multnomah County Dist. Court, 570 P. 2d 52 - Or: Supreme Court 1977 (available also at Google Scholar) ('There is no easy test for when the imposition of a sanction is a "criminal prosecution" within the meaning of the constitutional guarantees.') 
]
I recommend us to resolve this issue practically. 
What classes of charges are we putting into this Chargetype? Are violations in this Chargetype? If so, maybe we could rename it to violations, which are explicitly referenced in ORS 137.225. In that case, I'd be able to provide more concrete explanations of why violation convictions are eligible and why violation dismissals are not.

**Comment by wittejm** [comment]
We're defining Charge Types based how we identify them and how they are addressed specifically by the  expungement statute, so the charge types relevant to civil charges are:

- First check for traffic offenses: if the statute chapter is in 801 through 826, and it's a violation, it's a `TrafficViolation` 
- Then check the level, so if it has a level with `violation`, it's a `Violation`

Otherwise the civil offense has no level, so:
- Then If a charge has statute chapter 1 through 99 OR if the name contains "fugitive complaint" it's a  `CivilOffense` 
- If the name contains "contempt of court" it's a `ContemptOfCourt`

Written out this way, it appears we're treating "fugitive complaint" vs "contempt of court" inconsistently, because we're folding "fugitive complaint" into `CivilOffense`, whereas `ContemptOfCourt` is its own type.

After classifying charges by type, we treat both `CivilOffense` and `ContemptOfCourt` the same, in that both are always ineligible, and both do not block other charges.

So, I wonder if we should get rid of `ContemptOfCourt` as a Type and instead just classify those charges as `CivilOffense`.

**Comment by michaelzhang43** [comment]
So CivilOffense is just anything in chapter 1 through 99 and fugitive complaints? 
I can make a write up based off that. They're related enough to group together.

**Comment by wittejm** [comment]
completed with #1039
